In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# display all columns
pd.set_option('display.max_columns', None)
# display all rows
pd.set_option('display.max_rows', None)

In [2]:
datacomb_new = pd.read_csv('data_allthreeyears_combined_new1.csv')

/var/folders/5r/_w5lclyd5891k9z55_8lq98r0000gn/T/ipykernel_63454/564117682.py:1: DtypeWarning: Columns (19,24,27,28,30,31,38,39,45,46,48,49,50,52,53,66,67,78,79,82,85,87,110,111,112,115,122,124,133,135,139,140,143,144,145,146,147,148,149,150,151,153,156,157,162,163,164,165,166,167,168,169,170,178,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242) have mixed types. Specify dtype option on import or set low_memory=False.
  datacomb_new = pd.read_csv('data_allthreeyears_combined_new1.csv')


In [3]:
datacomb_new = datacomb_new.replace({'Gender - Selected Choice': 'Gender'})

In [4]:
datacomb_new['Location'].unique()

array(['India', 'Algeria', 'Egypt', 'France', 'Germany', 'Australia', nan,
       'South Korea', 'United States of America', 'Pakistan', 'Mexico',
       'Singapore', 'Italy', 'Taiwan', 'China', 'Argentina', 'Turkey',
       'Brazil', 'Nigeria', 'Chile', 'Japan', 'Canada', 'Indonesia',
       'Israel', 'Colombia', 'Russia',
       'United Kingdom of Great Britain and Northern Ireland', 'Ethiopia',
       'South Africa', 'Viet Nam', 'Kenya', 'Spain',
       'Iran, Islamic Republic of...', 'Cameroon', 'Tunisia', 'Peru',
       'Nepal', 'Morocco', 'Philippines', 'Ecuador', 'Thailand',
       'United Arab Emirates', 'Bangladesh', 'Netherlands', 'Zimbabwe',
       'Ghana', 'Portugal', 'Poland', 'Saudi Arabia', 'Romania',
       'Czech Republic', 'Malaysia', 'Sri Lanka', 'Hong Kong (S.A.R.)',
       'Ukraine', 'Belgium', 'Ireland', 'Greece', 'Switzerland', 'Sweden',
       'Austria', 'Belarus', 'Denmark', 'Uganda', 'Kazakhstan', 'Iraq',
       'Norway', 'Republic of Korea'], dtype=object)

In [5]:
datacomb_new['Location'].nunique()

67

In [6]:
list(datacomb_new.columns)

['Age',
 'Gender - Selected Choice',
 'Location',
 'Learning platforms tried - How well known are the platforms (platforms with good marketing) - Coursera',
 'Learning platforms tried - How well known are the platforms (platforms with good marketing) - edX',
 'Learning platforms tried - How well known are the platforms (platforms with good marketing) - Kaggle Learn Courses',
 'Learning platforms tried - How well known are the platforms (platforms with good marketing) - DataCamp',
 'Learning platforms tried - How well known are the platforms (platforms with good marketing) - Fast.ai',
 'Learning platforms tried - How well known are the platforms (platforms with good marketing) - Udacity',
 'Learning platforms tried - How well known are the platforms (platforms with good marketing) - Udemy',
 'Learning platforms tried - How well known are the platforms (platforms with good marketing) - LinkedIn Learning',
 'Learning platforms tried - How well known are the platforms (platforms with good 

In [7]:
datacomb_new['year'].dtype

dtype('int64')

In [8]:
datacomb_new.shape

(70006, 243)

In [9]:
categorical_columns = datacomb_new.select_dtypes(include=['object']).columns.tolist()
categorical_columns

['Age',
 'Gender - Selected Choice',
 'Location',
 'Learning platforms tried - How well known are the platforms (platforms with good marketing) - Coursera',
 'Learning platforms tried - How well known are the platforms (platforms with good marketing) - edX',
 'Learning platforms tried - How well known are the platforms (platforms with good marketing) - Kaggle Learn Courses',
 'Learning platforms tried - How well known are the platforms (platforms with good marketing) - DataCamp',
 'Learning platforms tried - How well known are the platforms (platforms with good marketing) - Fast.ai',
 'Learning platforms tried - How well known are the platforms (platforms with good marketing) - Udacity',
 'Learning platforms tried - How well known are the platforms (platforms with good marketing) - Udemy',
 'Learning platforms tried - How well known are the platforms (platforms with good marketing) - LinkedIn Learning',
 'Learning platforms tried - How well known are the platforms (platforms with good 

# drop the 'year' column

In [10]:
# drop the 'year' column

datacomb_new = datacomb_new.drop('year', axis = 1)

In [11]:
datacomb_new.shape

(70006, 242)

In [12]:
unique_counts = datacomb_new.nunique(dropna=False)

In [13]:
# unique_counts

In [14]:
binary_cols = unique_counts[unique_counts <= 2].index.tolist()

In [15]:
non_binary_cols = unique_counts[unique_counts > 2].index.tolist()
non_binary_cols

['Age',
 'Gender - Selected Choice',
 'Location',
 'Education level_attainedOrGGtoAttain',
 'Coding Experience (in years)',
 'Years in ML',
 'Job_title - Selected Choice',
 'Job_No.OfDSTeamMember',
 'Job_EmployerUsingML?',
 'Job_Salary',
 'Money Spent on ML/Cloud Computing',
 'Times used TPU']

In [16]:
# number of binary cols in the dataset
len(binary_cols)

230

In [17]:
datacomb_new.shape

(70006, 242)

In [18]:
datacomb_new.sample(2)

Age Gender - Selected Choice  Location  \
40715  60-69                      Man    Mexico   
37855  22-24                    Woman  Viet Nam   

      Learning platforms tried - How well known are the platforms (platforms with good marketing) - Coursera  \
40715                                                NaN                                                       
37855                                                NaN                                                       

      Learning platforms tried - How well known are the platforms (platforms with good marketing) - edX  \
40715                                                edX                                                  
37855                                                NaN                                                  

      Learning platforms tried - How well known are the platforms (platforms with good marketing) - Kaggle Learn Courses  \
40715                               Kaggle Learn Courses                                                                   
37855                                                NaN                                                                   

      Learning platforms tried - How well known are the platforms (platforms with good marketing) - DataCamp  \
40715                                                NaN                                                       
37855                                                NaN                                                       

      Learning platforms tried - How well known are the platforms (platforms with good marketing) - Fast.ai  \
40715                                                NaN                                                      
37855                                                NaN                                                      

      Learning platforms tried - How well known are the platforms (platforms with good marketing) - Udacity  \
40715                                                NaN                                                      
37855                                                NaN                                                      

      Learning platforms tried - How well known are the platforms (platforms with good marketing) - Udemy  \
40715                                              Udemy                                                    
37855                                                NaN                                                    

      Learning platforms tried - How well known are the platforms (platforms with good marketing) - LinkedIn Learning  \
40715                                                NaN                                                                
37855                                                NaN                                                                

      Learning platforms tried - How well known are the platforms (platforms with good marketing) - Cloud-certification programs (direct from AWS, Azure, GCP, or similar)  \
40715                                                NaN                                                                                                                     
37855                                                NaN                                                                                                                     

      Learning platforms tried - How well known are the platforms (platforms with good marketing) - University Courses (resulting in a university degree)  \
40715                                                NaN                                                                                                    
37855                                                NaN                                                                                                    

      Education level_attainedOrGGtoAttain Coding Experience (in years)  \
40715                            bachelors              

In [19]:
# binary_cols

In [20]:
# # sanity check only
# for i in binary_cols:
#     print(i)
#     print(datacomb_new[i].unique())
#     print('=====================')
    

In [21]:
# # sanity check only
# for i in non_binary_cols:
#     print(i)
#     print(datacomb_new[i].unique())
#     print('=====================')
    

In [22]:
non_binary_cols

['Age',
 'Gender - Selected Choice',
 'Location',
 'Education level_attainedOrGGtoAttain',
 'Coding Experience (in years)',
 'Years in ML',
 'Job_title - Selected Choice',
 'Job_No.OfDSTeamMember',
 'Job_EmployerUsingML?',
 'Job_Salary',
 'Money Spent on ML/Cloud Computing',
 'Times used TPU']

In [23]:
# check if the columns in non_binary_cols have NaN values
# columns with no NaN values may have the multi-colinearity problem when we one-hot-encode it with pd.get_dummies
for i in non_binary_cols:
    print(i, "---------", datacomb_new[i].isna().any().any())

Age --------- False
Gender - Selected Choice --------- True
Location --------- True
Education level_attainedOrGGtoAttain --------- True
Coding Experience (in years) --------- True
Years in ML --------- True
Job_title - Selected Choice --------- True
Job_No.OfDSTeamMember --------- True
Job_EmployerUsingML? --------- True
Job_Salary --------- True
Money Spent on ML/Cloud Computing --------- True
Times used TPU --------- True


In [24]:
datacomb_new[non_binary_cols].count()

Age                                     70006
Gender - Selected Choice                68707
Location                                65807
Education level_attainedOrGGtoAttain    66520
Coding Experience (in years)            68336
Years in ML                             60014
Job_title - Selected Choice             55880
Job_No.OfDSTeamMember                   36398
Job_EmployerUsingML?                    35954
Job_Salary                              34256
Money Spent on ML/Cloud Computing       34237
Times used TPU                          45776
dtype: int64

# Label Binary Columns to 0 and 1

In [25]:
datacomb_new[binary_cols] = np.where((datacomb_new[binary_cols] != 0) & (~datacomb_new[binary_cols].isna()), 1, 0)

In [26]:
datacomb_new.shape

(70006, 242)

In [27]:
datacomb_new['Job_title - Selected Choice'].isna().sum() # number of rows with the Job_title blank

14126

In [28]:
# drop rows with empty job title
datacomb_new = datacomb_new.dropna(subset = ['Job_title - Selected Choice'])

In [29]:
datacomb_new['Job_title - Selected Choice'].isna().sum() # number of rows with the Job_title blank is now 0

0

In [30]:
datacomb_new.shape

(55880, 242)

In [31]:
# drop rows with student as job title
datacomb_new = datacomb_new[datacomb_new['Job_title - Selected Choice'] != 'Student']
datacomb_new.shape

(43905, 242)

In [34]:
print(len(binary_cols))
print(len(non_binary_cols))

230
12


# Dropping cols we think is not associated to the job title

In [35]:
datacomb_new.shape

(43905, 242)

In [36]:
job_title_dict = {
    'Data Analyst (Business, Marketing, Financial, Quantitative, etc)': 'Data Analyst',
    'Product Manager': 'Product/Project/Program Manager',
    'Product/Project Manager': 'Product/Project/Program Manager',
    'Program/Project Manager':'Product/Project/Program Manager',
    'Machine Learning Engineer':'Machine Learning/ MLops Engineer'}

def replace_text(cell_value, replacements):
    if cell_value is not None and not pd.isna(cell_value):
        # Check if the cell_value is a float, and if so, convert it to a string.
        if isinstance(cell_value, float):
            cell_value = str(cell_value)
        cell_value = replacements.get(cell_value,cell_value)
    return cell_value

datacomb_new['Job_title - Selected Choice'] = datacomb_new['Job_title - Selected Choice'].apply(replace_text, replacements=job_title_dict)
datacomb_new['Job_title - Selected Choice'].unique()

array(['Data Scientist', 'Software Engineer', 'Research Scientist',
       'Other', 'Developer Advocate', 'Data Analyst', 'Data Engineer',
       'Currently not employed', 'Machine Learning/ MLops Engineer',
       'Engineer (non-software)', 'Teacher / professor', 'Statistician',
       'Manager (Program, Project, Operations, Executive-level, etc)',
       'Data Administrator', 'Data Architect',
       'Product/Project/Program Manager', 'Business Analyst',
       'Developer Relations/Advocacy', 'DBA/Database Engineer'],
      dtype=object)

In [37]:
Job_title = datacomb_new.pop('Job_title - Selected Choice')
datacomb_new.insert(len(datacomb_new.columns), 'Job_title - Selected Choice', Job_title)

/var/folders/5r/_w5lclyd5891k9z55_8lq98r0000gn/T/ipykernel_63454/2434528012.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  datacomb_new.insert(len(datacomb_new.columns), 'Job_title - Selected Choice', Job_title)


In [38]:
cols_to_drop = ['Job_No.OfDSTeamMember', 'Job_EmployerUsingML?','Money Spent on ML/Cloud Computing','Times used TPU','Job_title - Selected Choice']
datacomb_new_wo_Jtitle = datacomb_new.drop(cols_to_drop, axis = 1)


In [39]:
filtered_non_binary_cols = [item for item in non_binary_cols if item not in cols_to_drop]

In [40]:
filtered_non_binary_cols

['Age',
 'Gender - Selected Choice',
 'Location',
 'Education level_attainedOrGGtoAttain',
 'Coding Experience (in years)',
 'Years in ML',
 'Job_Salary']

In [41]:
encoded_df = pd.get_dummies(datacomb_new_wo_Jtitle, columns = filtered_non_binary_cols, prefix_sep=' - ')

In [42]:
encoded_df.shape

(43905, 346)

In [43]:
encoded_df[encoded_df['Popular IDEs - Click to write Choice 13'] ==1].count()

Learning platforms tried - How well known are the platforms (platforms with good marketing) - Coursera                                                                  4190
Learning platforms tried - How well known are the platforms (platforms with good marketing) - edX                                                                       4190
Learning platforms tried - How well known are the platforms (platforms with good marketing) - Kaggle Learn Courses                                                      4190
Learning platforms tried - How well known are the platforms (platforms with good marketing) - DataCamp                                                                  4190
Learning platforms tried - How well known are the platforms (platforms with good marketing) - Fast.ai                                                                   4190
Learning platforms tried - How well known are the platforms (platforms with good marketing) - Udacity                                  

In [44]:
encoded_df.drop('Age - 70+', axis = 1, inplace = True) # to remove multi-colinearity

In [45]:
encoded_df.shape # verifying that there is one less column

(43905, 345)

In [46]:
encoded_df.head()

Learning platforms tried - How well known are the platforms (platforms with good marketing) - Coursera  \
3                                                   1                                                        
7                                                   1                                                        
8                                                   1                                                        
10                                                  0                                                        
13                                                  1                                                        

    Learning platforms tried - How well known are the platforms (platforms with good marketing) - edX  \
3                                                   0                                                   
7                                                   1                                                   
8                                                   0                                                   
10                                                  0                                                   
13                                                  0                                                   

    Learning platforms tried - How well known are the platforms (platforms with good marketing) - Kaggle Learn Courses  \
3                                                   1                                                                    
7                                                   0                                                                    
8                                                   1                                                                    
10                                                  0                                                                    
13                                                  1                                                                    

    Learning platforms tried - How well known are the platforms (platforms with good marketing) - DataCamp  \
3                                                   0                                                        
7                                                   0                                                        
8                                                   0                                                        
10                                                  0                                                        
13                                                  0                                                        

    Learning platforms tried - How well known are the platforms (platforms with good marketing) - Fast.ai  \
3                                                   0                                                       
7                                                   0                                                       
8                                                   0                                                       
10                                                  0                                                       
13                                                  1                                                       

    Learning platforms tried - How well known are the platforms (platforms with good marketing) - Udacity  \
3                                                   0                                                       
7                                                   1                                                       
8                                                   0                                                       
10                                                  0                                                       
13                                                  1                                                       

    Lear

In [47]:
a = list(encoded_df.columns)
a.sort()
a

['Age - 18-21',
 'Age - 22-24',
 'Age - 25-29',
 'Age - 30-34',
 'Age - 35-39',
 'Age - 40-44',
 'Age - 45-49',
 'Age - 50-54',
 'Age - 55-59',
 'Age - 60-69',
 'Coding Experience (in years) - 1-2 years',
 'Coding Experience (in years) - 1-3 years',
 'Coding Experience (in years) - 10-20 years',
 'Coding Experience (in years) - 20+ years',
 'Coding Experience (in years) - 3-5 years',
 'Coding Experience (in years) - 5-10 years',
 'Coding Experience (in years) - < 1 years',
 'Coding Experience (in years) - I have never written code',
 'Education level_attainedOrGGtoAttain - bachelors',
 'Education level_attainedOrGGtoAttain - college without bachelors',
 'Education level_attainedOrGGtoAttain - doctoral',
 'Education level_attainedOrGGtoAttain - doctorate',
 'Education level_attainedOrGGtoAttain - high school and below',
 'Education level_attainedOrGGtoAttain - masters',
 'Education level_attainedOrGGtoAttain - professional deg',
 'Gender - Selected Choice - Man',
 'Gender - Selected Cho

## Random Forest

In [48]:
from sklearn.model_selection import train_test_split

rng = np.random.RandomState(seed=321)
X_train, X_test, y_train, y_test = train_test_split( encoded_df, Job_title , test_size=0.20, random_state= rng)

print( X_train.shape )
print( X_test.shape )

(35124, 345)
(8781, 345)


In [49]:
from sklearn.ensemble import RandomForestClassifier

rnd_clf = RandomForestClassifier( n_estimators=100, max_leaf_nodes=15, n_jobs=-1 )

rnd_clf.fit( X_train, y_train )

y_pred_rf = rnd_clf.predict( X_test )

In [50]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report
from pprint import pprint

def evaluate(test, pred):
    print(classification_report( test, pred ))
    # Calculate precision
    precision = precision_score(test, pred, average='micro')
    
    # Calculate recall
    recall = recall_score(test, pred, average='micro')
    
    print("Precision: ", precision)
    print("Recall: ", recall)


In [51]:
evaluate( y_test, y_pred_rf )

                                                              precision    recall  f1-score   support

                                            Business Analyst       0.00      0.00      0.00       369
                                      Currently not employed       0.41      0.94      0.57       990
                                       DBA/Database Engineer       0.00      0.00      0.00        51
                                          Data Administrator       0.00      0.00      0.00        17
                                                Data Analyst       0.37      0.33      0.35      1076
                                              Data Architect       0.00      0.00      0.00        22
                                               Data Engineer       0.00      0.00      0.00       288
                                              Data Scientist       0.32      0.81      0.46      1670
                                          Developer Advocate       0.00      0.00

/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_sta

In [52]:
# finding best parameters (1)

# from sklearn.model_selection import GridSearchCV

# params_to_test = {
#     'n_estimators':[10,25,50],#,100,200,500
#     'max_depth':[3,5,10] #15,20,25
# }

# #here you can put any parameter you want at every run, like random_state or verbosity
# rf_model = RandomForestClassifier(random_state=rng)
# #here you specify the CV parameters, number of folds, numberof cores to use...
# grid_search = GridSearchCV(rf_model, param_grid=params_to_test, cv=10, scoring='f1_macro', n_jobs=4)

# grid_search.fit(X_train, y_train)

# best_params = grid_search.best_params_ 

# #best_params is a dict you can pass directly to train a model with optimal settings 
# best_model = RandomForestClassifier(**best_params)

In [53]:
# best_params
# {'max_depth': 10, 'n_estimators': 50}

In [54]:
# best_model

In [55]:
# best_model.fit( X_train, y_train )
# best_model

In [56]:
# y_pred_rf = best_model.predict( X_test )

In [57]:

evaluate( y_test, y_pred_rf )

                                                              precision    recall  f1-score   support

                                            Business Analyst       0.00      0.00      0.00       369
                                      Currently not employed       0.41      0.94      0.57       990
                                       DBA/Database Engineer       0.00      0.00      0.00        51
                                          Data Administrator       0.00      0.00      0.00        17
                                                Data Analyst       0.37      0.33      0.35      1076
                                              Data Architect       0.00      0.00      0.00        22
                                               Data Engineer       0.00      0.00      0.00       288
                                              Data Scientist       0.32      0.81      0.46      1670
                                          Developer Advocate       0.00      0.00

/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_sta

In [58]:
# Finding best parameters (2)
# from sklearn.model_selection import RandomizedSearchCV
# from pprint import pprint
# # Number of trees in random forest
# n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# # Number of features to consider at every split
# max_features = ['auto', 'sqrt']
# # Maximum number of levels in tree
# max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
# max_depth.append(None)
# # Minimum number of samples required to split a node
# min_samples_split = [2, 5, 10]
# # Minimum number of samples required at each leaf node
# min_samples_leaf = [1, 2, 4]
# # Method of selecting samples for training each tree
# bootstrap = [True, False]
# # Create the random grid
# random_grid = {'n_estimators': n_estimators,
#                'max_features': max_features,
#                'max_depth': max_depth,
#                'min_samples_split': min_samples_split,
#                'min_samples_leaf': min_samples_leaf,
#                'bootstrap': bootstrap}
# pprint(random_grid)

In [59]:
# # !!! resource intensive !!!
# # Use the random grid to search for best hyperparameters
# # First create the base model to tune
# rf = RandomForestClassifier()
# # Random search of parameters, using 3 fold cross validation, 
# # search across 100 different combinations, and use all available cores
# rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 100, cv = 3, verbose=2, random_state=42, n_jobs = -1)
# # Fit the random search model
# rf_random.fit(X_train, y_train)


In [60]:
# rf_random.best_params_
# {'n_estimators': 1600,
#  'min_samples_split': 5,
#  'min_samples_leaf': 1,
#  'max_features': 'sqrt',
#  'max_depth': 70,
#  'bootstrap': False}

In [61]:
# rf_random.best_score_ 


In [62]:
# best_model_2 = RandomForestClassifier(**rf_random.best_params_)
# best_model_2

In [63]:
# best_model_2.fit(X_train, y_train)

In [64]:
# y_pred_best_2 = best_model_2.predict(X_test)

In [65]:
# evaluate( y_test, y_pred_best_2 )

# remove
# 'Currently not employed'

# merge

In [66]:
# from sklearn.model_selection import GridSearchCV
# # Create the parameter grid based on the results of random search 
# param_grid = {
#     'bootstrap': [True],
#     'max_depth': [80, 90, 100, 110],
#     'max_features': [2, 3],
#     'min_samples_leaf': [3, 4, 5],
#     'min_samples_split': [8, 10, 12],
#     'n_estimators': [100, 200, 300, 1000]
# }
# # Create a based model
# rf = RandomForestClassifier()
# # Instantiate the grid search model
# grid_search = GridSearchCV(estimator = rf, param_grid = param_grid, 
#                           cv = 3, n_jobs = -1, verbose = 2)

In [67]:
def print_all_columns(df):
    a = list(df.columns)
    a.sort()
    return a

## Exploration 1
1. Remove country

In [68]:
exploration_df_1 = datacomb_new_wo_Jtitle.copy()
exploration_df_1 = exploration_df_1[exploration_df_1.columns.drop(list(exploration_df_1.filter(regex='Location')))]

print_all_columns(exploration_df_1)
exploration_df_1.shape

(43905, 236)

In [69]:
filtered_non_binary_cols_dum = filtered_non_binary_cols.copy()
exploration_1_encoded_df = pd.get_dummies(exploration_df_1, columns = filtered_non_binary_cols_dum.remove('Location'), prefix_sep=' - ')
exploration_1_encoded_df.shape

(43905, 279)

In [70]:
exploration_1_encoded_df.drop('Age - 70+', axis = 1, inplace = True) # to remove multi-colinearity

In [71]:
print_all_columns(exploration_1_encoded_df)

['Age - 18-21',
 'Age - 22-24',
 'Age - 25-29',
 'Age - 30-34',
 'Age - 35-39',
 'Age - 40-44',
 'Age - 45-49',
 'Age - 50-54',
 'Age - 55-59',
 'Age - 60-69',
 'Coding Experience (in years) - 1-2 years',
 'Coding Experience (in years) - 1-3 years',
 'Coding Experience (in years) - 10-20 years',
 'Coding Experience (in years) - 20+ years',
 'Coding Experience (in years) - 3-5 years',
 'Coding Experience (in years) - 5-10 years',
 'Coding Experience (in years) - < 1 years',
 'Coding Experience (in years) - I have never written code',
 'Education level_attainedOrGGtoAttain - bachelors',
 'Education level_attainedOrGGtoAttain - college without bachelors',
 'Education level_attainedOrGGtoAttain - doctoral',
 'Education level_attainedOrGGtoAttain - doctorate',
 'Education level_attainedOrGGtoAttain - high school and below',
 'Education level_attainedOrGGtoAttain - masters',
 'Education level_attainedOrGGtoAttain - professional deg',
 'Gender - Selected Choice - Man',
 'Gender - Selected Cho

In [72]:
# train test split
X_train, X_test, y_train, y_test = train_test_split( exploration_1_encoded_df, Job_title , test_size=0.20, random_state= rng)

print( X_train.shape )
print( X_test.shape )

(35124, 278)
(8781, 278)


In [73]:

# exploration_1_rnd_clf = RandomForestClassifier(**rf_random.best_params_)

# exploration_1_rnd_clf.fit( X_train, y_train )

# exploration_1_y_pred_rf = exploration_1_rnd_clf.predict( X_test )

In [74]:
# evaluate(y_test, exploration_1_y_pred_rf)

## "Final"

In [75]:
hyper_parameters = {'n_estimators': 1600,
 'min_samples_split': 5,
 'min_samples_leaf': 1,
 'max_features': 'sqrt',
 'max_depth': 70,
 'bootstrap': False}

In [146]:
jobs_df = pd.DataFrame(y_train)
jobs_count = pd.DataFrame(jobs_df.groupby('Job_title - Selected Choice')['Job_title - Selected Choice'].count())
jobs_count.index.name = None

jobs_df_test = pd.DataFrame(y_test)
jobs_count_test = pd.DataFrame(jobs_df_test.groupby('Job_title - Selected Choice')['Job_title - Selected Choice'].count())
jobs_count_test.index.name = None

jobs_count_all = pd.concat([jobs_count, jobs_count_test], axis=1)
jobs_count_all.columns=['train','test']

jobs_count_all.sort_values('train')

# jobs_df.groupby('Job_title - Selected Choice').count()
y_test['Data Administrator','Developer Advocate','Data Architect','Developer Relations/Advocacy']


KeyError: 'key of type tuple not found and not a MultiIndex'

In [77]:
final_rf = RandomForestClassifier(**hyper_parameters)
final_rf

RandomForestClassifier(bootstrap=False, max_depth=70, min_samples_split=5,
                       n_estimators=1600)

In [78]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)
final_rf.fit(X_train, y_train)

(35124, 278)
(35124,)
(8781, 278)
(8781,)


RandomForestClassifier(bootstrap=False, max_depth=70, min_samples_split=5,
                       n_estimators=1600)

In [79]:
final_y_pred = final_rf.predict(X_test)
final_y_pred

array(['Data Analyst', 'Data Scientist', 'Data Analyst', ...,
       'Data Analyst', 'Data Scientist', 'Data Scientist'], dtype=object)

In [80]:
# this one the last final model
evaluate(y_test, final_y_pred)

                                                              precision    recall  f1-score   support

                                            Business Analyst       0.15      0.01      0.02       361
                                      Currently not employed       0.65      0.93      0.77       984
                                       DBA/Database Engineer       0.00      0.00      0.00        63
                                          Data Administrator       0.00      0.00      0.00        12
                                                Data Analyst       0.37      0.47      0.42      1071
                                              Data Architect       0.00      0.00      0.00        29
                                               Data Engineer       0.29      0.01      0.03       273
                                              Data Scientist       0.42      0.69      0.52      1680
                                          Developer Advocate       0.00      0.00

/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_sta

In [81]:
final_y_pred_proba = final_rf.predict_proba(X_test)
final_y_pred_proba

array([[0.0625    , 0.00354167, 0.00140625, ..., 0.07119792, 0.00895833,
        0.00942708],
       [0.024375  , 0.00395833, 0.00473958, ..., 0.07302083, 0.01348958,
        0.03322917],
       [0.08552083, 0.00921875, 0.01723958, ..., 0.09526042, 0.01854167,
        0.00916667],
       ...,
       [0.06104167, 0.00776042, 0.        , ..., 0.00682292, 0.00208333,
        0.00453125],
       [0.03161458, 0.        , 0.00791667, ..., 0.06239583, 0.00661458,
        0.00151042],
       [0.06604167, 0.        , 0.00557292, ..., 0.05046875, 0.01229167,
        0.00494792]])

In [82]:
final_y_pred_proba.shape

(8781, 19)

In [83]:
len(set(Job_title))

19

In [84]:
import numpy as np

def mark_largest_values(matrix, x=1):
    result_matrix = np.zeros_like(matrix)
    indices = []
    for i in range(matrix.shape[0]):
        row = matrix[i, :]
        indices_of_largest_values = np.argsort(-row)[:x]
        # print(indices_of_largest_values)
        # print(row[indices_of_largest_values])
        result_matrix[i, indices_of_largest_values] = 1
        indices.append(indices_of_largest_values)

    return result_matrix, indices

def get_x_recommendation(model, x_test, x=1):
    pred_proba = model.predict_proba(x_test)
    
    matrix, indices = mark_largest_values(pred_proba, x)

    x_recommendation = [ [model.classes_[i] for i in idx]for idx in indices  ]

    return x_recommendation

matrix, indices = mark_largest_values(final_y_pred_proba)

final_rf.classes_

array(['Business Analyst', 'Currently not employed',
       'DBA/Database Engineer', 'Data Administrator', 'Data Analyst',
       'Data Architect', 'Data Engineer', 'Data Scientist',
       'Developer Advocate', 'Developer Relations/Advocacy',
       'Engineer (non-software)', 'Machine Learning/ MLops Engineer',
       'Manager (Program, Project, Operations, Executive-level, etc)',
       'Other', 'Product/Project/Program Manager', 'Research Scientist',
       'Software Engineer', 'Statistician', 'Teacher / professor'],
      dtype=object)

In [85]:
recommended_titles_3 = [ [final_rf.classes_[i] for i in idx]for idx in indices  ] # sorted by best probability
recommended_titles_3

[['Data Analyst'],
 ['Data Scientist'],
 ['Data Analyst'],
 ['Data Scientist'],
 ['Software Engineer'],
 ['Currently not employed'],
 ['Data Scientist'],
 ['Data Scientist'],
 ['Data Scientist'],
 ['Data Scientist'],
 ['Data Scientist'],
 ['Software Engineer'],
 ['Currently not employed'],
 ['Data Analyst'],
 ['Data Scientist'],
 ['Software Engineer'],
 ['Data Analyst'],
 ['Research Scientist'],
 ['Data Scientist'],
 ['Software Engineer'],
 ['Machine Learning/ MLops Engineer'],
 ['Data Scientist'],
 ['Currently not employed'],
 ['Currently not employed'],
 ['Data Scientist'],
 ['Other'],
 ['Currently not employed'],
 ['Machine Learning/ MLops Engineer'],
 ['Machine Learning/ MLops Engineer'],
 ['Product/Project/Program Manager'],
 ['Research Scientist'],
 ['Software Engineer'],
 ['Software Engineer'],
 ['Data Scientist'],
 ['Software Engineer'],
 ['Currently not employed'],
 ['Data Scientist'],
 ['Software Engineer'],
 ['Data Analyst'],
 ['Research Scientist'],
 ['Data Scientist'],
 ['

In [86]:
y_test_2 = [[y] for y in y_test]
print(y_test_2[:3])
print(recommended_titles_3[:3])
# evaluate(y_test_2,recommended_titles_3)

[['Software Engineer'], ['Software Engineer'], ['Data Analyst']]
[['Data Analyst'], ['Data Scientist'], ['Data Analyst']]


In [87]:

from sklearn.preprocessing import MultiLabelBinarizer
def eval_multi(test, pred):
    test_multi = [[y] for y in test]
    mlb = MultiLabelBinarizer()
    
    mlb_fit = mlb.fit(test_multi)
    print(mlb_fit.classes_)
    
    test_transformed = mlb_fit.transform(test_multi)
    pred_transformed = mlb_fit.transform(pred)
    print(test_transformed)
    print(pred_transformed)
    
    evaluate(test_transformed, pred_transformed)

eval_multi(y_test, recommended_titles_3)

['Business Analyst' 'Currently not employed' 'DBA/Database Engineer'
 'Data Administrator' 'Data Analyst' 'Data Architect' 'Data Engineer'
 'Data Scientist' 'Developer Advocate' 'Developer Relations/Advocacy'
 'Engineer (non-software)' 'Machine Learning/ MLops Engineer'
 'Manager (Program, Project, Operations, Executive-level, etc)' 'Other'
 'Product/Project/Program Manager' 'Research Scientist'
 'Software Engineer' 'Statistician' 'Teacher / professor']
[[0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
              precision    recall  f1-score   support

           0       0.15      0.01      0.02       361
           1       0.65      0.93      0.77       984
           2       0.00      0.00      0.00        63
           3       0.00      0.00      0.00        12
           4       0.37      0.

/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [88]:
# compare best probability n pred
# best_prob = np.array(recommended_titles_3)[:, 0]
# evaluate(final_y_pred, best_prob)

In [89]:
a = list(exploration_1_encoded_df.columns)
a.sort()
a

['Age - 18-21',
 'Age - 22-24',
 'Age - 25-29',
 'Age - 30-34',
 'Age - 35-39',
 'Age - 40-44',
 'Age - 45-49',
 'Age - 50-54',
 'Age - 55-59',
 'Age - 60-69',
 'Coding Experience (in years) - 1-2 years',
 'Coding Experience (in years) - 1-3 years',
 'Coding Experience (in years) - 10-20 years',
 'Coding Experience (in years) - 20+ years',
 'Coding Experience (in years) - 3-5 years',
 'Coding Experience (in years) - 5-10 years',
 'Coding Experience (in years) - < 1 years',
 'Coding Experience (in years) - I have never written code',
 'Education level_attainedOrGGtoAttain - bachelors',
 'Education level_attainedOrGGtoAttain - college without bachelors',
 'Education level_attainedOrGGtoAttain - doctoral',
 'Education level_attainedOrGGtoAttain - doctorate',
 'Education level_attainedOrGGtoAttain - high school and below',
 'Education level_attainedOrGGtoAttain - masters',
 'Education level_attainedOrGGtoAttain - professional deg',
 'Gender - Selected Choice - Man',
 'Gender - Selected Cho

In [90]:
# visualize (only can visualize 1 tree)
# from sklearn.tree import export_graphviz

# export_graphviz(final_rf,
#                 feature_names=exploration_1_encoded_df.columns,
#                 filled=True,
#                 rounded=True)

# os.system('dot -Tpng tree.dot -o tree.png')


## Post final exploration - 1

In [91]:
pfexp_df = exploration_df_1.copy()

pfexp_df = pfexp_df[pfexp_df.columns.drop(list(pfexp_df.filter(regex='Popular IDEs')))]
list(pfexp_df.columns)

['Age',
 'Gender - Selected Choice',
 'Learning platforms tried - How well known are the platforms (platforms with good marketing) - Coursera',
 'Learning platforms tried - How well known are the platforms (platforms with good marketing) - edX',
 'Learning platforms tried - How well known are the platforms (platforms with good marketing) - Kaggle Learn Courses',
 'Learning platforms tried - How well known are the platforms (platforms with good marketing) - DataCamp',
 'Learning platforms tried - How well known are the platforms (platforms with good marketing) - Fast.ai',
 'Learning platforms tried - How well known are the platforms (platforms with good marketing) - Udacity',
 'Learning platforms tried - How well known are the platforms (platforms with good marketing) - Udemy',
 'Learning platforms tried - How well known are the platforms (platforms with good marketing) - LinkedIn Learning',
 'Learning platforms tried - How well known are the platforms (platforms with good marketing) - 

In [92]:
xcl_loc = filtered_non_binary_cols.copy()
xcl_loc.remove('Location')

In [93]:
print_all_columns(pfexp_df)

['Age',
 'Coding Experience (in years)',
 'Education level_attainedOrGGtoAttain',
 'Gender - Selected Choice',
 'Job_JobScope - Analyze and understand data to influence product or business decisions',
 'Job_JobScope - Build and/or run a machine learning service that operationally improves my product or workflows',
 'Job_JobScope - Build and/or run the data infrastructure that my business uses for storing, analyzing, and operationalizing data',
 'Job_JobScope - Build prototypes to explore applying machine learning to new areas',
 'Job_JobScope - Do research that advances the state of the art of machine learning',
 'Job_JobScope - Experimentation and iteration to improve existing ML models',
 'Job_Salary',
 'Learning platforms tried - How well known are the platforms (platforms with good marketing) - Cloud-certification programs (direct from AWS, Azure, GCP, or similar)',
 'Learning platforms tried - How well known are the platforms (platforms with good marketing) - Coursera',
 'Learning

In [94]:
# ordinal encodings
ord_encodings = pd.read_csv('ordinal_encodings_2.csv')
# print(pfexp_df.Job_Salary.unique())
included_columns = ['Age', 'Education level_attainedOrGGtoAttain', 'Coding Experience (in years)', 'Years in ML', 
                    'Job_Salary']
nominal_features_order_dict = {}
for col in included_columns:
    nominal_features_order_dict[col] = dict(zip(ord_encodings[col], ord_encodings[col+'_encoded']))



pfexp_df.replace(nominal_features_order_dict,inplace=True)
print_all_columns(pfexp_df)
gender_dict = {'Man': 1, 'Woman': 2}
pfexp_df.replace(gender_dict,inplace=True)
pfexp_df.replace({np.NaN:0},inplace=True)

for col in xcl_loc:
    print('')
    print(col)
    print(pfexp_df[col].unique())


Age
[ 8.  3. 10.  5.  7.  2.  4.  9.  1.  6.  0.]

Gender - Selected Choice
[1. 2. 0.]

Education level_attainedOrGGtoAttain
[2. 3. 5. 4. 0. 1. 6. 7.]

Coding Experience (in years)
[6. 7. 3. 5. 4. 1. 0. 2.]

Years in ML
[2. 5. 6. 3. 1. 4. 7. 0.]

Job_Salary
[12. 18.  0. 22. 20. 17.  6. 15. 19. 26. 27. 24.]


In [95]:
pfexp_df

X_train, X_test, y_train, y_test = train_test_split( pfexp_df, Job_title, test_size=0.20, random_state= rng)

print( X_train.shape )
print( X_test.shape )

(35124, 221)
(8781, 221)


In [96]:
# Use the random grid to search for best hyperparameters
# # First create the base model to tune
# rf = RandomForestClassifier()
# # Random search of parameters, using 3 fold cross validation, 
# # search across 100 different combinations, and use all available cores
# rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 30, cv = 3, verbose=2, random_state=42, n_jobs = -1)
# # Fit the random search model
# rf_random.fit(X_train, y_train)

In [97]:
# rf_random.best_params_


In [98]:
so_called_best_param = {'n_estimators': 1200,
 'min_samples_split': 2,
 'min_samples_leaf': 2,
 'max_features': 'sqrt',
 'max_depth': 50,
 'bootstrap': False}
final_rf = RandomForestClassifier(**so_called_best_param)
final_rf

RandomForestClassifier(bootstrap=False, max_depth=50, min_samples_leaf=2,
                       n_estimators=1200)

In [99]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)
final_rf.fit(X_train, y_train)

(35124, 221)
(35124,)
(8781, 221)
(8781,)


RandomForestClassifier(bootstrap=False, max_depth=50, min_samples_leaf=2,
                       n_estimators=1200)

In [100]:
final_y_pred = final_rf.predict(X_test)
final_y_pred

array(['Currently not employed', 'Data Analyst', 'Currently not employed',
       ..., 'Data Scientist', 'Data Scientist', 'Data Scientist'],
      dtype=object)

In [101]:
evaluate(y_test, final_y_pred)

                                                              precision    recall  f1-score   support

                                            Business Analyst       0.25      0.00      0.01       371
                                      Currently not employed       0.54      0.94      0.68       995
                                       DBA/Database Engineer       1.00      0.02      0.03        59
                                          Data Administrator       0.00      0.00      0.00        20
                                                Data Analyst       0.37      0.46      0.41      1052
                                              Data Architect       0.00      0.00      0.00        19
                                               Data Engineer       0.80      0.03      0.05       315
                                              Data Scientist       0.41      0.68      0.51      1622
                                          Developer Advocate       0.00      0.00

/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_sta

In [102]:
recommendation_3 = get_x_recommendation(final_rf, X_test, x=3)

eval_multi(y_test, recommendation_3)

['Business Analyst' 'Currently not employed' 'DBA/Database Engineer'
 'Data Administrator' 'Data Analyst' 'Data Architect' 'Data Engineer'
 'Data Scientist' 'Developer Advocate' 'Developer Relations/Advocacy'
 'Engineer (non-software)' 'Machine Learning/ MLops Engineer'
 'Manager (Program, Project, Operations, Executive-level, etc)' 'Other'
 'Product/Project/Program Manager' 'Research Scientist'
 'Software Engineer' 'Statistician' 'Teacher / professor']
[[0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 1 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 [0 1 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
              precision    recall  f1-score   support

           0       0.14      0.25      0.18       371
           1       0.41      1.00      0.58       995
           2       0.14      0.02      0.03        59
           3       0.00      0.00      0.00        20
           4       0.20      0.

/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [105]:
from sklearn.model_selection import GridSearchCV
# Create the parameter grid based on the results of random search 
param_grid = {
    'bootstrap': [True, False],
    'max_depth': [40,45,50,55,60],
    'max_features': ['auto', 'sqrt'],
    'min_samples_leaf': [2, 3],
    'min_samples_split': [2, 3],
    'n_estimators': [10,15,20,30,50,1000, 1100, 1150, 1200, 1250]
}
# Create a based model
rf = RandomForestClassifier()
# Instantiate the grid search model
grid_search = GridSearchCV(estimator = rf, param_grid = param_grid, 
                          cv = 3, n_jobs = -1, verbose = 2)

In [106]:
grid_rf = grid_search.fit(X_train, y_train)

Fitting 3 folds for each of 400 candidates, totalling 1200 fits
[CV] END bootstrap=True, max_depth=40, max_features=auto, min_samples_leaf=2, min_samples_split=2, n_estimators=1000; total time=   0.0s
[CV] END bootstrap=True, max_depth=40, max_features=auto, min_samples_leaf=2, min_samples_split=2, n_estimators=1250; total time=   0.0s
[CV] END bootstrap=True, max_depth=40, max_features=auto, min_samples_leaf=2, min_samples_split=3, n_estimators=1150; total time=   0.0s
[CV] END bootstrap=True, max_depth=40, max_features=auto, min_samples_leaf=3, min_samples_split=2, n_estimators=1000; total time=   0.0s
[CV] END bootstrap=True, max_depth=40, max_features=auto, min_samples_leaf=3, min_samples_split=2, n_estimators=1150; total time=   0.0s
[CV] END bootstrap=True, max_depth=40, max_features=auto, min_samples_leaf=3, min_samples_split=3, n_estimators=1000; total time=   0.0s
[CV] END bootstrap=True, max_depth=40, max_features=sqrt, min_samples_leaf=2, min_samples_split=2, n_estimators=10

/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(


[CV] END bootstrap=True, max_depth=40, max_features=auto, min_samples_leaf=2, min_samples_split=2, n_estimators=1000; total time=   0.0s
[CV] END bootstrap=True, max_depth=40, max_features=auto, min_samples_leaf=2, min_samples_split=3, n_estimators=1100; total time=   0.0s
[CV] END bootstrap=True, max_depth=40, max_features=auto, min_samples_leaf=2, min_samples_split=3, n_estimators=1250; total time=   0.0s
[CV] END bootstrap=True, max_depth=40, max_features=auto, min_samples_leaf=3, min_samples_split=2, n_estimators=1150; total time=   0.0s
[CV] END bootstrap=True, max_depth=40, max_features=auto, min_samples_leaf=3, min_samples_split=3, n_estimators=1000; total time=   0.0s
[CV] END bootstrap=True, max_depth=40, max_features=sqrt, min_samples_leaf=2, min_samples_split=2, n_estimators=1000; total time= 1.1min
[CV] END bootstrap=True, max_depth=40, max_features=sqrt, min_samples_leaf=2, min_samples_split=2, n_estimators=1100; total time= 2.1min
[CV] END bootstrap=True, max_depth=40, ma

/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:425: FitFailedWarning: 
600 fits failed out of a total of 1200.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
195 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/base.py", line 1145, in wrapper
    estimator._validate_params()
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/base.py", line 638, in _val

In [107]:
grid_rf.best_params_
# {'bootstrap': False,
#  'max_depth': 55,
#  'max_features': 'sqrt',
#  'min_samples_leaf': 2,
#  'min_samples_split': 3,
#  'n_estimators': 1100}

{'bootstrap': False,
 'max_depth': 55,
 'max_features': 'sqrt',
 'min_samples_leaf': 2,
 'min_samples_split': 3,
 'n_estimators': 1100}

In [108]:
from sklearn.model_selection import GridSearchCV
# Create the parameter grid based on the results of random search 
param_grid = {
    'bootstrap': [True, False],
    'max_depth': [40,45,50,55,60],
    'max_features': ['sqrt'],
    'min_samples_leaf': [2, 3],
    'min_samples_split': [2, 3],
    'n_estimators': [10,15,20,30,50]
}
# Create a based model
rf = RandomForestClassifier()
# Instantiate the grid search model
grid_search = GridSearchCV(estimator = rf, param_grid = param_grid, 
                          cv = 3, n_jobs = -1, verbose = 2)

grid_rf = grid_search.fit(X_train, y_train)
grid_rf

Fitting 3 folds for each of 400 candidates, totalling 1200 fits
[CV] END bootstrap=True, max_depth=40, max_features=auto, min_samples_leaf=2, min_samples_split=3, n_estimators=10; total time=   0.0s
[CV] END bootstrap=True, max_depth=40, max_features=sqrt, min_samples_leaf=2, min_samples_split=3, n_estimators=50; total time=   3.2s
[CV] END bootstrap=True, max_depth=40, max_features=sqrt, min_samples_leaf=2, min_samples_split=3, n_estimators=50; total time=   3.1s
[CV] END bootstrap=True, max_depth=40, max_features=sqrt, min_samples_leaf=3, min_samples_split=2, n_estimators=10; total time=   0.6s
[CV] END bootstrap=True, max_depth=40, max_features=sqrt, min_samples_leaf=3, min_samples_split=2, n_estimators=10; total time=   0.6s


/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(


[CV] END bootstrap=True, max_depth=40, max_features=auto, min_samples_leaf=2, min_samples_split=3, n_estimators=15; total time=   0.0s
[CV] END bootstrap=True, max_depth=40, max_features=sqrt, min_samples_leaf=2, min_samples_split=3, n_estimators=30; total time=   1.9s
[CV] END bootstrap=True, max_depth=40, max_features=sqrt, min_samples_leaf=2, min_samples_split=3, n_estimators=30; total time=   2.0s
[CV] END bootstrap=True, max_depth=40, max_features=sqrt, min_samples_leaf=2, min_samples_split=3, n_estimators=30; total time=   1.7s
[CV] END bootstrap=True, max_depth=40, max_features=sqrt, min_samples_leaf=2, min_samples_split=3, n_estimators=50; total time=   3.1s
[CV] END bootstrap=True, max_depth=40, max_features=auto, min_samples_leaf=2, min_samples_split=3, n_estimators=10; total time=   0.0s
[CV] END bootstrap=True, max_depth=40, max_features=sqrt, min_samples_leaf=2, min_samples_split=2, n_estimators=50; total time=   3.0s
[CV] END bootstrap=True, max_depth=40, max_features=sqr

/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:425: FitFailedWarning: 
600 fits failed out of a total of 1200.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
501 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/base.py", line 1145, in wrapper
    estimator._validate_params()
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/base.py", line 638, in _val

GridSearchCV(cv=3, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'bootstrap': [True, False],
                         'max_depth': [40, 45, 50, 55, 60],
                         'max_features': ['auto', 'sqrt'],
                         'min_samples_leaf': [2, 3],
                         'min_samples_split': [2, 3],
                         'n_estimators': [10, 15, 20, 30, 50]},
             verbose=2)

In [109]:
grid_rf.best_params_

# {'bootstrap': False,
#  'max_depth': 50,
#  'max_features': 'sqrt',
#  'min_samples_leaf': 2,
#  'min_samples_split': 3,
#  'n_estimators': 50}

{'bootstrap': False,
 'max_depth': 50,
 'max_features': 'sqrt',
 'min_samples_leaf': 2,
 'min_samples_split': 3,
 'n_estimators': 50}

[CV] END bootstrap=True, max_depth=60, max_features=sqrt, min_samples_leaf=2, min_samples_split=2, n_estimators=50; total time=   3.1s
[CV] END bootstrap=True, max_depth=60, max_features=sqrt, min_samples_leaf=2, min_samples_split=2, n_estimators=50; total time=   3.1s
[CV] END bootstrap=True, max_depth=60, max_features=sqrt, min_samples_leaf=3, min_samples_split=2, n_estimators=50; total time=   2.8s
[CV] END bootstrap=True, max_depth=60, max_features=sqrt, min_samples_leaf=3, min_samples_split=3, n_estimators=30; total time=   1.7s
[CV] END bootstrap=False, max_depth=40, max_features=auto, min_samples_leaf=3, min_samples_split=2, n_estimators=20; total time=   0.0s
[CV] END bootstrap=False, max_depth=40, max_features=auto, min_samples_leaf=3, min_samples_split=2, n_estimators=50; total time=   0.0s
[CV] END bootstrap=False, max_depth=40, max_features=auto, min_samples_leaf=3, min_samples_split=3, n_estimators=10; total time=   0.0s
[CV] END bootstrap=False, max_depth=40, max_features

In [110]:
best_grid = {'bootstrap': False,
 'max_depth': 50,
 'max_features': 'sqrt',
 'min_samples_leaf': 2,
 'min_samples_split': 3,
 'n_estimators': 50}

In [111]:
best_random = {'bootstrap': False,
 'max_depth': 55,
 'max_features': 'sqrt',
 'min_samples_leaf': 2,
 'min_samples_split': 3,
 'n_estimators': 1100}

In [122]:
def RandomForest_HyperParameter_Evaluator(param, X_train, y_train, X_test, y_test):
    rf = RandomForestClassifier(**param)
    rf.fit(X_train, y_train)
    y_pred = rf.predict(X_test)
    evaluate(y_test, y_pred)
    return rf

In [124]:
best_grid_forest = RandomForest_HyperParameter_Evaluator(best_grid, X_train, y_train, X_test, y_test)
best_grid_forest.feature_importances_

                                                              precision    recall  f1-score   support

                                            Business Analyst       0.00      0.00      0.00       371
                                      Currently not employed       0.54      0.94      0.69       995
                                       DBA/Database Engineer       1.00      0.02      0.03        59
                                          Data Administrator       0.00      0.00      0.00        20
                                                Data Analyst       0.36      0.44      0.40      1052
                                              Data Architect       0.00      0.00      0.00        19
                                               Data Engineer       0.55      0.02      0.04       315
                                              Data Scientist       0.40      0.65      0.50      1622
                                          Developer Advocate       0.00      0.00

/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_sta

array([4.16913849e-02, 9.21265045e-03, 1.31202652e-02, 6.40999484e-03,
       1.20583077e-02, 7.81456204e-03, 2.41196532e-03, 5.35892331e-03,
       1.04797647e-02, 5.49048426e-03, 3.64206932e-03, 8.59156298e-03,
       3.80618604e-02, 4.11549995e-02, 8.30803853e-03, 1.28591917e-02,
       1.66081038e-02, 7.80903263e-03, 1.58849632e-03, 9.48058365e-03,
       1.47901801e-02, 1.77704589e-02, 5.61849506e-03, 1.09232361e-03,
       6.97086960e-03, 7.07643899e-04, 1.11379683e-04, 1.13571276e-02,
       1.12829591e-02, 2.24730672e-03, 1.94856240e-04, 2.25381790e-03,
       8.17149443e-04, 2.06914499e-04, 6.70416537e-04, 3.07727957e-04,
       0.00000000e+00, 3.59569520e-05, 1.68586212e-03, 2.08600235e-04,
       3.34931454e-05, 3.35585458e-02, 1.08964682e-02, 9.57739669e-03,
       8.85316512e-03, 8.55615718e-03, 1.61635458e-03, 9.14440288e-03,
       6.16296999e-03, 2.60872734e-03, 2.65790589e-03, 1.54693771e-03,
       2.62507691e-04, 1.38593355e-03, 1.91460158e-03, 9.89753938e-03,
      

In [118]:
RandomForest_HyperParameter_Evaluator(best_random, X_train, y_train, X_test, y_test)


/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_sta

                                                              precision    recall  f1-score   support

                                            Business Analyst       0.25      0.00      0.01       371
                                      Currently not employed       0.54      0.94      0.69       995
                                       DBA/Database Engineer       1.00      0.02      0.03        59
                                          Data Administrator       0.00      0.00      0.00        20
                                                Data Analyst       0.37      0.46      0.41      1052
                                              Data Architect       0.00      0.00      0.00        19
                                               Data Engineer       0.73      0.03      0.05       315
                                              Data Scientist       0.41      0.68      0.51      1622
                                          Developer Advocate       0.00      0.00

                                                              precision    recall  f1-score   support

                                            Business Analyst       0.25      0.00      0.01       371
                                      Currently not employed       0.54      0.93      0.68       995
                                       DBA/Database Engineer       1.00      0.02      0.03        59
                                          Data Administrator       0.00      0.00      0.00        20
                                                Data Analyst       0.37      0.45      0.40      1052
                                              Data Architect       0.00      0.00      0.00        19
                                               Data Engineer       0.56      0.03      0.05       315
                                              Data Scientist       0.40      0.64      0.49      1622
                                          Developer Advocate       0.00      0.00

/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_sta

In [121]:
X_train.sample()

Age  Gender - Selected Choice  \
66282  1.0                       1.0   

       Learning platforms tried - How well known are the platforms (platforms with good marketing) - Coursera  \
66282                                                  0                                                        

       Learning platforms tried - How well known are the platforms (platforms with good marketing) - edX  \
66282                                                  0                                                   

       Learning platforms tried - How well known are the platforms (platforms with good marketing) - Kaggle Learn Courses  \
66282                                                  0                                                                    

       Learning platforms tried - How well known are the platforms (platforms with good marketing) - DataCamp  \
66282                                                  0                                                        

       Learning platforms tried - How well known are the platforms (platforms with good marketing) - Fast.ai  \
66282                                                  0                                                       

       Learning platforms tried - How well known are the platforms (platforms with good marketing) - Udacity  \
66282                                                  0                                                       

       Learning platforms tried - How well known are the platforms (platforms with good marketing) - Udemy  \
66282                                                  0                                                     

       Learning platforms tried - How well known are the platforms (platforms with good marketing) - LinkedIn Learning  \
66282                                                  0                                                                 

       Learning platforms tried - How well known are the platforms (platforms with good marketing) - Cloud-certification programs (direct from AWS, Azure, GCP, or similar)  \
66282                                                  0                                                                                                                      

       Learning platforms tried - How well known are the platforms (platforms with good marketing) - University Courses (resulting in a university degree)  \
66282                                                  0                                                                                                     

       Education level_attainedOrGGtoAttain  Coding Experience (in years)  \
66282                                   3.0                           2.0   

       Popular programming language - Python  \
66282                                      1   

       Popular programming language - R  Popular programming language - SQL  \
66282                                 0                                   0   

       Popular programming language - C  Popular programming language - C#  \
66282                                 0                                  0   

       Popular programming language - C++  \
66282                                   0   

       Popular programming language - Java  \
66282                                    0   

       Popular programming language - Javascript  \
66282                                          0   

       Popular programming language - Bash  \
66282                                    0   

       Popular programming language - PHP  \
66282                                   0   

       Popular programming language - MATLAB  \
66282                                      0   

       Popular programming language - Julia  \
66282                                     0   

       Popular programming language - Go  \
66282                                  0   

       Popular hosted notebook products - Kaggle Notebooks  \
66282                               

In [127]:
best_random_2 = best_random.copy()
print(best_random_2)
best_random_2['max_depth'] = 15
best_random_2['max_features'] = 5
print(best_random_2)
RandomForest_HyperParameter_Evaluator(best_random_2, X_train, y_train, X_test, y_test)


{'bootstrap': False, 'max_depth': 55, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'min_samples_split': 3, 'n_estimators': 1100}
{'bootstrap': False, 'max_depth': 15, 'max_features': 5, 'min_samples_leaf': 2, 'min_samples_split': 3, 'n_estimators': 1100}
                                                              precision    recall  f1-score   support

                                            Business Analyst       0.00      0.00      0.00       371
                                      Currently not employed       0.44      0.98      0.61       995
                                       DBA/Database Engineer       0.00      0.00      0.00        59
                                          Data Administrator       0.00      0.00      0.00        20
                                                Data Analyst       0.36      0.37      0.37      1052
                                              Data Architect       0.00      0.00      0.00        19
                            

/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_sta

RandomForestClassifier(bootstrap=False, max_depth=15, max_features=5,
                       min_samples_leaf=2, min_samples_split=3,
                       n_estimators=1100)